@startuml ddd
'https://plantuml.com/sequence-diagram

autonumber

title DSIM.Flashing Min Changes

participant Actor
participant SC #lightgreen
participant ext_DynamicSIM.ActivationPageService as DSIMFlashing #lightyellow
participant ext_NAPIProxy.NAPIService as NAPIProxy #lightgreen 
participant Ensemble #lightgreen
participant OTA #lightgreen
participant componentSMSPusher.glassfish as SMSPusher #lightgreen
participant SMS_Router as SMSRouter #lightgreen

Actor -->> SC: Событие регистрации в сети с временным IMSIt \n(через ??? и Ensemble)
SC -> DSIMFlashing: Сообщение об изменении IMSI на карте (через MQ-очередь)
activate DSIMFlashing

activate NAPIProxy
DSIMFlashing -> NAPIProxy: GET /getServiceList
NAPIProxy->Ensemble: Получение SOC с кодами базовых фичеров 
activate Ensemble
Ensemble-->NAPIProxy: SOC
deactivate Ensemble
DSIMFlashing<--NAPIProxy: SOC
deactivate NAPIProxy

DSIMFlashing -> OTA: <font color=blue> POST triggerImsiReplacement (для смены IMSI на SIM-карте)
activate OTA
DSIMFlashing<--OTA:OK (200) с response из ["0", "STATUS_CODE_0_SUCCESS"]
deactivate DSIMFlashing
activate SMSRouter
OTA->SMSRouter:SMS  с командами перепрошивки SIM
deactivate OTA
SMSRouter -> OTA: Отчет о доставке
deactivate SMSRouter
activate OTA #lightgreen
alt возникла ошибка доставки
    DSIMFlashing<-OTA:Передача асинхронного ответа на  URL из переменной sicap-notify-url с ошибкой srvState = 4
    activate DSIMFlashing
    DSIMFlashing-->OTA: OK
    DSIMFlashing ->> SMSPusher : PushSMSToMQ (SMS на временный номер абонента без запроса уведомления о доставке о неуспешной активации)
    break
        note over DSIMFlashing #lightgreen:  завершение сценария без удаления временного абонента \n Возможность перезапуска процесса перепрошивки
        deactivate DSIMFlashing
    end
    alt "непонятно" (srvState=5, srvCode=3)
        DSIMFlashing<-OTA:Передача асинхронного ответа на  URL из переменной sicap-notify-url с ошибкой srvState=5, srvCode=3
        activate DSIMFlashing
        DSIMFlashing-->OTA: OK
        deactivate DSIMFlashing
        loop Дополнительные проверки успешности перепрошивки
            DSIMFlashing ->> SMSPusher : PushSMSToMQ (SMS Type=0 на временный  номер абонента с запросом уведомления о доставке.)
            activate DSIMFlashing
            activate SMSPusher
            DSIMFlashing ->> SMSPusher : PushSMSToMQ (SMS Type=0 на постоянный  номер абонента с запросом уведомления о доставке.)
            deactivate DSIMFlashing
            activate SMSPusher

            DSIMFlashing<-SMSPusher:Отчет о доставке на постоянный номер
            deactivate SMSPusher
            activate DSIMFlashing

            break SMS на постоянный номер доставлен, перепрошивка успешна
                DSIMFlashing ->  OTA: <font color=blue> POST ChangeSubscription  ( для удаления временного абонента.)
                OTA -> OTA: удаление временных IMSI и MSISDN из базы OTA
                DSIMFlashing<--OTA:OK (200)
                note over DSIMFlashing #lightgreen:удаление временного абонента во всех системах\nDSTK, HLR (через Ensemble и SC), ....\n
                deactivate DSIMFlashing
            end
    
            DSIMFlashing<-SMSPusher:Отчет о доставке на временный номер
            activate DSIMFlashing
            deactivate SMSPusher
            break SMS на временный номер доставлен- нужна повторная перепрошивка 
                DSIMFlashing ->  OTA: <font color=blue> POST BreakSubscriptionWaiting  ( прерывание ожидания POST ChangeSubscription на OTA)
                OTA -> OTA: прерывание ожидания ChangeSubscription
                DSIMFlashing<--OTA:OK (200)
                note over DSIMFlashing #lightgreen:  завершение сценария без удаления временного абонента \nВозможность перезапуска процесса перепрошивки при событии\n на сети с временным IMSIt
                deactivate DSIMFlashing
            end
        end
    else получен отчет об успешной доставке
        OTA -> OTA: удаление временных IMSI и MSISDN из базы OTA
        DSIMFlashing<-OTA:Передача асинхронного ответа на  URL из переменной sicap-notify-url без ошибки
        activate DSIMFlashing
        DSIMFlashing-->OTA: OK
        DSIMFlashing ->> SMSPusher : PushSMSToMQ (SMS на постоянный  номер абонента без запроса уведомления о доставке.)
        deactivate DSIMFlashing
        deactivate OTA
        note over DSIMFlashing #lightgreen:удаление временного абонента во всех системах\nDSTK, HLR (через Ensemble и SC), ....\n
    end
end

@enduml